### ISSUE TITLE
Randomly generated duplicated style functions

### ISSUE THREAD

**Issue by carlosmuvi** [airbnb/paris#106]
Sometimes Paris generates duplicated functions for `style` and `styleBuilder` in some of the views.

![image](https://user-images.githubusercontent.com/625017/53876963-dc7e8400-3fff-11e9-88e2-797df9089a6f.png)

Happening from time to time, usually after changing branches. Rebuilding the project fixes it.

**Comment by ngsilverman** [comment]
Thanks for the report @carlosmuvi ! I have yet to run into this issue, and unless I'm able to reproduce it it'll be challenging to fix. If you were able to create a minimal project which faces this issue that would be super helpful.

**Comment by ngsilverman** [comment]
I'm closing this since I doubt this issue can be addressed by the Paris library itself.
