### ISSUE TITLE
Context in styles. Dynamic tinting for drawables

### ISSUE THREAD

**Issue by qbait** [airbnb/paris#117]
Is there a way to have `resources` or `context` when defining styles? I would like to tint my drawable dynamically...

```
        @Style
        val PINK_STYLE = startTrialBannerStyle {
            badgeStyle {
                background(resources.getDrawable(R.drawable.round_rect_pink).setTint(Color.RED))
            }
        }
```

**Comment by ngsilverman** [comment]
@qbait that's not possible at the moment, but a good alternative could be to add a custom styleable attributes to set the tint color separately, see https://github.com/airbnb/paris/wiki/Custom-View-Attributes
