### ISSUE TITLE
Applying style for MaterialButton

### ISSUE THREAD

**Issue by qbait** [airbnb/paris#119]
I'm trying to apply regular and outlined style to `MaterialButton`

```
    companion object {

        @Style
        val PRIMARY_STYLE = subscriptionRowStyle {
            buttonStyle {
                R.style.Widget_MaterialComponents_Button
            }
        }

        @Style
        val SECONDARY_STYLE = subscriptionRowStyle {

            buttonStyle {
                R.style.Widget_MaterialComponents_Button_Outlined
            }
        }

        @Style
        val DEFAULT_STYLE = PRIMARY_STYLE
    }
```

my `attrs`
```
    <declare-styleable name="SubscriptionRow">
        <attr name="buttonStyle" format="reference" />
    </declare-styleable>
```

However, it doesn't work. What am I doing wrong?

**Comment by ngsilverman** [comment]
@qbait the following syntax is incorrect:

```kotlin
buttonStyle {
    R.style.Widget_MaterialComponents_Button
}
```

You can do:
```kotlin
buttonStyle(R.style.Widget_MaterialComponents_Button)

// Or

buttonStyle {
    add(R.style.Widget_MaterialComponents_Button)
    // This enables you to add more styles or override specific attributes if you need.
}
```

**Comment by NurseyitTursunkulov** [comment]
In my case, when I apply style button is not outlined:
    <style name = "SexButtonSelected" parent="Widget.MaterialComponents.Button.OutlinedButton">
        <item name="android:textColor">@color/red</item>
    </style>
    <style name = "SexButtonNotSelected" parent="Widget.MaterialComponents.Button.TextButton">
        <item name="android:textColor">@color/colorTitle</item>
    </style>

       boy_btn.style {
                            add(R.style.SexButtonSelected)
                        }
                        girl_btn.style {
                            add(R.style.SexButtonNotSelected)
                        }
