### ISSUE TITLE
Apply Style to TextView

### ISSUE THREAD

**Issue by Vrungel322** [airbnb/paris#120]
I need to apply style to my textView, my style has  attribute
`        <item name="android:textAllCaps">false</item>
`
When I apply it via` textView.style(R.style.ButtonFilled) `(via library method) - "caps" attribute do not work, and all text become caps true

**Comment by ngsilverman** [comment]
@Vrungel322 this is likely due to a bug introduced in `1.3.0` where a default `textAppearance` is being applied as part of your style, which ends up overriding your `textAllCaps`. You can try using an earlier version for now. I plan on trying to fix this issue soon.

**Comment by ngsilverman** [comment]
@Vrungel322 this should be fixed in `1.3.1`.
