### ISSUE TITLE
@Attr not work well  with gradle 3.6.0-rc01

### ISSUE THREAD

**Issue by qiushui95** [airbnb/paris#122]
e: G:\Code\Clone\paris\sample\build\tmp\kapt3\stubs\debug\com\airbnb\paris\sample\SectionView.java:30: ����: �����ݵ�����: <��ֵ>�޷�ת��Ϊint
    @com.airbnb.paris.annotations.StyleableChild(value = null)
                                                         ^

gradle 3.5.3 works well

**Comment by ngsilverman** [comment]
More information would be helpful here. Can I see the code that's using `@StyleableChild`?
