### ISSUE TITLE
Styles defined for views in different fragments affecting each other

### ISSUE THREAD

**Issue by idrisadetunmbi** [airbnb/paris#129]
**Description**: I am getting some very weird behaviors with views (of the same type) defined in different fragments (and sometimes in the same fragment too). [Here](https://github.com/idrisadetunmbi/androidlibissueproject) is a sample project where I defined a material component `TextInputLayout` proxy and used it in the fragments.

Navigating from FragmentA to FragmentB back and forth would reflect this behavior. The closest explanation I am thinking might be the issue is the [View recycling](https://github.com/airbnb/paris/wiki/View-Recycling) but the assertion did not crash my app at any point. I have spent a whole day on this and can't quite figure out what I am doing wrong. Any help would be appreciated.

**Comment by idrisadetunmbi** [comment]
@ngsilverman, please can you help here. Thanks.

**Comment by ngsilverman** [comment]
@idrisadetunmbi can you please explain what the weird behaviors are that you're observing?

A few notes:
1. The same attributes assertion only checks [linked styles](https://github.com/airbnb/epoxy/wiki/Paris-Integration-(Dynamic-Styling)), you don't appear to be using them in your test project.
2. Epoxy has a [Paris integration](https://github.com/airbnb/epoxy/wiki/Paris-Integration-(Dynamic-Styling)), which you can use rather than the onBind listener. If you do, and if you enable validation of model usage as described [here](https://github.com/airbnb/epoxy/wiki/Paris-Integration-(Dynamic-Styling)), then it will run the same attributes assertion when the models are bound.

**Comment by idrisadetunmbi** [comment]
@ngsilverman, thanks for taking the time to respond on time. I am using the `onBind` listener just for a quick demo to reproduce the bug.

My main implementation uses databinding for the models with a `style` variable defined in the layout. Something like below:

```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

        <variable
            name="style"
            type="com.airbnb.paris.styles.Style" />

        <variable
            name="styleRes"
            type="Integer" />
    </data>

    <com.google.android.material.textfield.TextInputLayout
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        styleRes="@{styleRes}"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:style="@{style}">

        <com.google.android.material.textfield.TextInputEditText
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </com.google.android.material.textfield.TextInputLayout>
</layout>
```

The issue I am experiencing is: instances of the model generated by the above databinding layout have the view styles applied to them overlapping into each other even in different fragments. This is not peculiar to models generated by databinding as I have tried using custom views as well with the same result.

![FragmentA-ActualScreen](https://user-images.githubusercontent.com/30455641/78172990-e961e700-744e-11ea-9b36-f49e7be22736.png)
![FragmentB-ActualScreen](https://user-images.githubusercontent.com/30455641/78172997-ecf56e00-744e-11ea-91bd-3243d1967135.png)
![FragmentA with FragmentB's style overlapping](https://user-images.githubusercontent.com/30455641/78173004-eebf3180-744e-11ea-8357-d46e6059c051.png)

**Comment by ngsilverman** [comment]
@idrisadetunmbi databinding is not something I've looked into for Paris usage, I'd have to see how you've implemented the `style` and `styleRes` attributes to help debug. Alternatively, if you can update your example app using best practices, and the issue is still present, I can take another look there.

**Comment by idrisadetunmbi** [comment]
@ngsilverman, the implementations for `style` and `styleRes` are basic binding adapters as in below:

```
@BindingAdapter("styleRes")
fun setStyleRes(view: MaterialTextView, styleRes: Int?) {
    styleRes?.let { view.style(it) }
}

@BindingAdapter("style")
fun setStyle(view: TextInputLayout, style: Style?) {
    style?.let { view.style(it) }
}
```

 I have used a custom view with epoxy integration and the issue has not been happening so far, Thanks a lot. I have a few issues with this setup, however, which would not have been the case if I was not using it with paris/epoxy integration or databinding.

1. `@Styleable` does not work with [layout overloads](https://github.com/airbnb/epoxy/wiki/Generating-Models-from-View-Annotations#layout-overloads) because I can't use a `defaultLayout` property in the `ModelView` annotation.

2. For my specific use-case, I am trying to use a material components `TextInputLayout` and creating a custom view (with this set up from it) does not allow specifying a layout style outside of epoxy/paris (or admittedly, maybe because I don't have the experience on how to do that).

**Comment by idrisadetunmbi** [comment]
Thanks, @ngsilverman, I figured the issue is with the view recycling and I have modified the binding adapters/custom views (that I cannot use the epoxy integration with) to set default styles before adding new styles to override them:

```
@BindingAdapter("style")
fun setStyle(view: TextInputLayout, style: Style?) {
    style?.let {
        view.style {
            add(DEFAULT_STYLE)
            add(it)
        }
    }
}
```
