### ISSUE TITLE
Epoxy Grid Carousel Breaking with Models created with Paris

### ISSUE THREAD

**Issue by idrisadetunmbi** [airbnb/paris#130]
I created a very simple [app](https://github.com/idrisadetunmbi/androidlibissueproject) that uses an epoxy `GridCarousel`, a Paris styled custom `TextView` and I have spent a couple of hours trying to figure out why the carousel does not display as a grid. A model created with data-binding works perfectly, however. (please see attached project for different scenarios).

```
// TextView
@Styleable
@ModelView
class CustomText(context: Context) : AppCompatTextView(context) {
    companion object {
        @Style
        val DEFAULT_STYLE = R.style.Text
    }
}

// GridCarousel
@ModelView(autoLayout = ModelView.Size.WRAP_WIDTH_MATCH_HEIGHT)
class VerticalGridCarousel(context: Context) : Carousel(context) {
    override fun createLayoutManager(): LayoutManager {
        return GridLayoutManager(context, 2, GridLayoutManager.VERTICAL, false)
    }
}

// usage in fragment
verticalGridCarousel {
            id("Carousel")
            models(texts.map { text ->
                CustomTextModel_().apply {
                    id(text)
                    styleBuilder {
                        it.text(text)
                        it.textSizeDp(30)
                        it.layoutWidth(ViewGroup.LayoutParams.MATCH_PARENT)
                        it.layoutHeight(ViewGroup.LayoutParams.WRAP_CONTENT)
                    }
                }
            })
        }
```

Result:
![photo5780765783163515770](https://user-images.githubusercontent.com/30455641/78380084-38cd2200-75cb-11ea-89e3-f50ba20f792a.jpg)

**Comment by idrisadetunmbi** [comment]
Hi @ngsilverman, can you assist here please? Thanks.

**Comment by ngsilverman** [comment]
@idrisadetunmbi what's the expected result? Setting the text view with to `MATCH_PARENT` could be an issue here.

As a side note, why are you using a style builder on the Epoxy model rather than setting those attributes in the `Text` style?

**Comment by idrisadetunmbi** [comment]
Thanks for checking this out @ngsilverman. I opened a similar issue in the Epoxy repo and it looks like the problem is with Epoxy (or my set up of it) rather than Paris. I will close this out now (apologies I had it delayed).

As per the side note, on the assumption that I understand your question correctly, I am trying to make the model reusable and the style (`DEFAULT_STYLE = R.style.Text`) in the model definition is meant to be the base which other instances of the model can override, hence the reason I am using the `styleBuilder` to define the style for that particular instance (could have used the `style` property of the model too).

I am quite new to Epoxy and Paris, so if my usage or understanding as described above is wrong, I would appreciate you correcting me. Thanks again.
