### ISSUE TITLE
Generate Kotlin extensions for @Styleable views

### ISSUE THREAD

**Issue by ngsilverman** [airbnb/paris#22]
Rather than going through the Paris class (`Paris.style(view)...`) extensions could be generated for each view type:
```kotlin
fun View.style(style: Style) {
    ViewStyleApplier(this).apply(style)
}

fun View.style(init: ViewStyleApplier.StyleBuilder.() -> Unit) {
    ViewStyleApplier.StyleBuilder().let {
        it.init()
        it.applyTo(this)
    }
}

// Linked style
fun View.styleGreen() {
    ViewStyleApplier(this).apply(R.style.Green)
}
```

In action:
```kotlin
Paris.style(view).apply(R.style.Green)
// Could be replaced by:
view.style(R.style.Green)

Paris.styleBuilder(view)
        .add(R.style.MyGreenTextView)
        .textSizeRes(R.dimen.my_text_size_small)
        .apply();
// Could be replaced by:
view.style {
    add(R.style.MyGreenTextView)
    textSizeRes(R.dimen.my_text_size_small)
}

Paris.style(view).applyGreen()
// Could be replaced by:
view.styleGreen()
```

cc @elihart

**Comment by elihart** [comment]
I think it would also be interesting to generate a style builder for each custom view.
```kotlin
val style: Style = myViewStyle {
    add(R.style.MyGreenTextView)
    textSizeRes(R.dimen.my_text_size_small)
}
```

I would be interested in working on this!

**Comment by ngsilverman** [comment]
Agreed, standalone style builders would be useful as well. In fact it's probably the use case that benefits the most, `MyViewStyleApplier.StyleBuilder()...` is a mouthful. :)

Would love to have you work on it of course! I'd recommend starting by implementing `SkyKotlinFile` to complement [SkyJavaClass](https://github.com/airbnb/paris/blob/master/paris-processor/src/main/java/com/airbnb/paris/processor/framework/SkyJavaClass.kt).

**Comment by ngsilverman** [comment]
Documenting some of the options we've talked about.

## Applying a style to a view

### View extensions in view packages
```kotlin
package android.view

fun View.style(style: Style) {
    // ...
}
```
```kotlin
package android.widget

fun TextView.style(style: Style) {
    // ...
}
```
**Pros:** super short and clear syntax.
**Cons:** lots of competing imports, using the wrong one could result in some attributes being ignored.

### View extensions in the same file
```kotlin
package com.application.or.library.module

fun View.style(style: Style) {
    // ...
}

fun TextView.style(style: Style) {
  // ...
}
```
**Pros:** super short and clear syntax, single import per module.
**Cons:** there are still competing imports from other modules, using them could result in some attributes being ignored.

### Internal view extensions in the same file
```kotlin
package com.application.or.library.module

internal fun View.style(style: Style) {
    // ...
}

internal fun TextView.style(style: Style) {
  // ...
}
```
**Pros:** super short and clear syntax, impossible to import the wrong extensions.
**Cons:** the extensions aren't available at all in downstream modules.

### View extensions in the same file + configurable visiblity
```kotlin
// Turn it on for the last module that declares styleable views and off for its dependencies
@ParisConfig(publicExtensions = true)
```
**Pros:** super short and clear syntax, impossible to import the wrong extensions and extensions are available downstream.
**Cons:** advanced configuration required, might require running the processor on a module with no styleable views just to have access to the extensions.

### Explicit functions
```kotlin
fun styleView(view: View, style: Style) {
    // ...
}

fun styleTextView(view: TextView, style: Style) {
    // ...
}
```
**Pros:** very hard to use the wrong function.
**Cons:** verbose syntax, no better than `Paris.style(view).apply(style)`.

### View extensions in the same package, one file per module
```kotlin
package com.airbnb.paris

internal fun View.style(style: Style) {
    // ...
}
```
```kotlin
package com.airbnb.paris

internal fun MyView.style(style: Style) {
  // ...
}
```
**Pros:** ???
**Cons:** ???
