### ISSUE TITLE
Kotlin substyle builders

### ISSUE THREAD

**Issue by ngsilverman** [airbnb/paris#23]
Current substyle builder in Kotlin:
```kotlin
Paris.styleBuilder(myView)
        .titleStyle {
            it.textColor(...)
            it.textSize(...)
        }
```

Ideally we'd be able to write:
```kotlin
Paris.styleBuilder(myView)
        .titleStyle {
            textColor(...)
            textSize(...)
        }
```

It's currently unclear to me how to achieve this while maintaining good Java interop.

cc @elihart

**Comment by elihart** [comment]
I have the same issue for supporting a kotlin style builder epoxy models. The only way I can see to achieve this is to generate kotlin extensions functions. I don't know that it is worth it for the slight improvement int syntax (eg receiver instead of it)
