### ISSUE TITLE
Look into incremental annotation processor support

### ISSUE THREAD

**Issue by ngsilverman** [airbnb/paris#24]
https://docs.gradle.org/4.7/userguide/java_plugin.html#sec:incremental_annotation_processing

Given the limitations it seems unlikely that we'd be able to use it now (can't use the `Trees` API), but perhaps in the future.

**Comment by elihart** [comment]
An approach like https://github.com/JakeWharton/butterknife/pull/1546 could potentially make this really easy

**Comment by neugartf** [comment]
Any update here? :)

**Comment by elihart** [comment]
yep, i'm actually working on this this week
