### ISSUE TITLE
Add support for android:hint and android:inputType

### ISSUE THREAD

**Issue by ioterateam** [airbnb/paris#25]
my style has "android:hint" and "android:inputType", im styling for EditText, but when i apply with Paris, it's not working, please help, thanks

**Comment by ngsilverman** [comment]
Just added support for `hint`: https://github.com/airbnb/paris/commit/9fe12780c345184bee30e3de549ccf110e24d44d

Will add `inputType` soon.

**Comment by ioterateam** [comment]
thanks for your response, sorry i can't contribute for now because i'm still developing my own project, i will wait for your next update, thanks so much for your fast response 👍

**Comment by ngsilverman** [comment]
@ioterateam I've added support for both attributes and published a snapshot of the next planned version. You can use it by changing the dependencies in `build.gradle` to:
```gradle
dependencies {
    implementation 'com.airbnb.android:paris:1.1.0-SNAPSHOT'
    // If you are using Paris annotations
    annotationProcessor 'com.airbnb.android:paris-processor:1.1.0-SNAPSHOT'
}
```
Let me know if you run into any issues.

**Comment by ioterateam** [comment]
when will you upload the next version? or that `1.1.0-SNAPSHOT` version is already uploaded? because i change my `build.gradle` using that version and get error : `Error:(41, 20) Failed to resolve: com.airbnb.android:paris:1.1.0-SNAPSHOT`

**Comment by ioterateam** [comment]
thanks, it's work like a charm now! i will tell you if i get any issue in the future, good luck!

**Comment by ioterateam** [comment]
i just check for `inputType:textPassword`, there is a bug, it's make `textVisiblePassword `instead of `textPassword`. Please recheck it, thanks

**Comment by ngsilverman** [comment]
@ioterateam would you mind creating a new issue for this? I should be able to take a look in the next few days.

**Comment by ioterateam** [comment]
okay i will create a new issue then, hang on
