### ISSUE TITLE
Paris style not work for styling AppBarLayout and Toolbar

### ISSUE THREAD

**Issue by ioterateam** [airbnb/paris#44]
I try to styling my `AppBarLayout` and `Toolbar` programmatically using **Paris**.
But, it's not work, may be because **Paris** _not support_ it yet?
Really need help for styling that `AppBarLayout` and `Toolbar` programmatically.
And i wonder, in xml i use `android:theme` for styling `AppBarLayout` and `Toolbar`, is it same with styling right?

**Comment by ngsilverman** [comment]
@ioterateam like I pointed out last time, the supported view types and attributes are documented here: https://github.com/airbnb/paris/wiki/Supported-View-Types-and-Attributes

`AppBarLayout` and `Toolbar` both extend from `ViewGroup` and `View` so some of their attributes are supported. Which ones are you interested in exactly?

`android:theme` is related to but not the same as a style.

**Comment by ioterateam** [comment]
Actually i want to move `android:theme` from xml attribute of `AppBarLayout` and `Toolbar` to _programmatically implementation_, but when i using Paris, it's not work. So it's a different function?

**Comment by ngsilverman** [comment]
That's not supported at the moment. What does your theme declaration look like?

**Comment by ioterateam** [comment]
My theme declaration looks like : 

> MyMain.xml
```
...
      <android.support.design.widget.AppBarLayout
        android:id="@+id/activity_home_appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:theme="@style/AppTheme.AppBarOverlay">

        <android.support.v7.widget.Toolbar
            android:id="@+id/activity_home_toolbar"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:background="@color/colorPrimary"
            app:popupTheme="@style/AppTheme.PopupOverlay"
            app:titleTextColor="@color/colorMaterialWhite"
            app:theme="@style/ToolbarColoredBackArrow" />

        <android.support.design.widget.TabLayout
            android:id="@+id/activity_home_tabs"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            app:tabGravity="center"
            app:tabMode="fixed" />
    </android.support.design.widget.AppBarLayout>
...
```

> MyStyle.xml
```
...
    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.ActionBar">
        <item name="colorPrimary">@color/colorMaterialWhite</item>
        <item name="colorControlNormal">@color/colorPrimaryDark</item>
        <item name="colorControlHighlight">@color/colorAccent</item>
    </style>

    <style name="ToolbarColoredBackArrow" parent="AppTheme">
        <item name="android:textColor">@color/colorMaterialWhite</item>
        <item name="android:textColorSecondary">@color/colorMaterialWhite</item>
    </style>
...
```

**Comment by ngsilverman** [comment]
Do you want to create the styles programmatically or just apply them that way? Either way it's not supported by the library at this time, but themes are something I plan on exploring in the next few months.

**Comment by ioterateam** [comment]
Yes i want to styling it programmatically. Aw, that's mean i must wait for it for a few months ..
