### ISSUE TITLE
Why drawableStart attr is not consumable?

### ISSUE THREAD

**Issue by Kolyall** [airbnb/paris#56]
`drawableLeft` is consumable in TextView https://github.com/airbnb/paris/wiki/Supported-View-Types-and-Attributes 
but Why `drawableStart` attr is not consumable?

**Comment by ngsilverman** [comment]
@Kolyall support for each attribute has to be added individually, `drawableStart` simply hasn't been needed/added yet. If you're interested in contributing support for that attribute you can take a look at https://github.com/airbnb/paris/blob/master/paris/src/main/java/com/airbnb/paris/proxies/TextViewProxy.java to get you started. 😄
