### ISSUE TITLE
Can you add a annotation to generate the method `layout`?

### ISSUE THREAD

**Issue by Kolyall** [airbnb/paris#58]
https://github.com/airbnb/paris/blob/dac749254462c2e4eaa6ee899afcf97753a8facd/sample/src/main/java/com/airbnb/paris/sample/MarqueeView.java#L46

Can you add an annotation `@Layout` for view class to generate the method? 
For exapmle 

```
@Layout(id = R.layout.view_marquee)
@Styleable("MarqueeView")
public class MarqueeView extends BaseView {
```

**Comment by ngsilverman** [comment]
@Kolyall what would be gained from using an annotation rather than overriding a method?

**Comment by Kolyall** [comment]
The same code style for all views and quick navigation to `*.xml` file, because you will know that `R.layout.view_marquee` will be always on top of the class file

**Comment by ngsilverman** [comment]
@Kolyall I'd recommend using an abstract base view class with a `@LayoutRes abstract int layout();` method. You could probably use a custom code style to ensure that particular method is always at the top of classes. Using annotation processing for this doesn't make sense/isn't worth it in my opinion.
