### ISSUE TITLE
Is any way to move views with Paris to library?

### ISSUE THREAD

**Issue by Kolyall** [airbnb/paris#59]
I trying to move my custom view to library module but the error occurs:

```
@Attr(R.styleable.MyButton_image) //Attribute value must be constant
    public void setImage(@DrawableRes int image) {
        setImageToView(image);
    }
```

```
Attribute value must be constant
error: element value must be a constant expression |  
-- | --
```

**Comment by ngsilverman** [comment]
@Kolyall make sure to read the documentation about library modules: https://github.com/airbnb/paris/wiki/Library-Modules

You'll want to apply the Butter Knife Gradle plugin and use `R2` instead of `R` in annotation parameters.
