### ISSUE TITLE
How to apply @StyleableChild if constructor only View(Context context) is using?

### ISSUE THREAD

**Issue by Kolyall** [airbnb/paris#61]
for example I use  in code 
```
MyView item = new MyView(getActivity());
Paris.style(item).apply(R.style.MyViewStyle_Big);
```
But you said that  [// Make sure to call Paris.style(this).apply(attrs) during initialization ](https://github.com/airbnb/paris#styling-subviews), how to apply it in constructor `View(Context context)`?
```
@Styleable("MyView ")
public class MyView extends LinearLayout {

    @BindView(R.id.imageView) ImageView mImageView;
    @StyleableChild(R.styleable.DjItemView_titleStyle)
    @BindView(R.id.titleView) TextView mTitleView;
    @StyleableChild(R.styleable.DjItemView_subTitleStyle)
    @BindView(R.id.subTitleView) TextView mSubTitleView;

    public MyView (Context context) {
        super(context);
    }
```

**Comment by ngsilverman** [comment]
@Kolyall ah, I can see how the documentation might need clarifying. There's no need to call `Paris.style(this).apply(attrs);` if there's no `AttributeSet`, as is the case when a view is constructed with its single parameter constructor.
