### ISSUE TITLE
Api16 crash due to invalid resource type for a default attribute in the ProxyView

### ISSUE THREAD

**Issue by kristiyanP** [airbnb/paris#70]
# Problem
- Pre-conditions : Api16
- Version api: any (1.0.0 included and also master branch)

### Paris is not working because of an unexpected type attribute parsing.

[Paris_View](https://github.com/airbnb/paris/blob/master/paris/src/main/res/values/attrs.xml#L4
) adds support for **android:layout_marginEnd,android:layout_marginStart** which are not defined in api16. 

For an unknown reason Android platform 16 returns the id of this **resourceres/drawable-xhdpi/popup_inline_error_above_holo_light.9.png** which leads to the exception
```java
 java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x3
``` 
caused in [TypedArrayTypedArrayWrapper](https://github.com/airbnb/paris/blob/master/paris/src/main/java/com/airbnb/paris/typed_array_wrappers/TypedArrayTypedArrayWrapper.kt#L40)

# Possible Solution
Check the type before getting the actual value of the attributes with

```kotlin 
typedArray.peekValue(index).type
```
for example in this case the function would be something like this

``` kotlin
override fun getDimensionPixelSize(index: Int): Int =
    if (typedArray.peekValue(index).type != TypedValue.TYPE_DIMENSION) -1
    else typedArray.getDimensionPixelSize(index, -1)
```
This obviously will fix the issue but it may lead to unwanted results in same cases. For example what would happen if the attribute is actually of the same type but is related to a different one?

# How to reproduce in sample app
Change [style(attrs)](https://github.com/airbnb/paris/blob/master/sample/src/main/java/com/airbnb/paris/sample/SectionView.kt#L51) with
```kotlin
 Paris.style(this).apply(R.style.Blue)
```
# Discussion
This is issue is extremely important for us as we need to support Api16.
We are about to go in production and would like to have it fixed. 
We can also provide PR, just let us know what you think about it.

**Comment by plnice** [comment]
Same with `android:elevation` on some devices with Android 4.4 (Samsung ones), crashes with
```
 java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
```

**Comment by ngsilverman** [comment]
@kristiyanP your repro steps for the sample app, is that without modifying `R.style.Blue`? If so, I don't see what's not compatible with API v16 in there. 🤔 

I think the issue could be worked around by using styles that don't have unsupported attributes (like `android:layout_marginEnd`) based on the API version.

Here's a suggestion on how to properly fix it: if you take a look at `ViewProxy`, its `@Attr` functions are usually already annotated with the appropriate `@RequiresApi`:
https://github.com/airbnb/paris/blob/master/paris/src/main/java/com/airbnb/paris/proxies/ViewProxy.kt#L155

The annotation processor could then generate an additional condition in the `StyleApplier` classes:
```java

  @Override
  protected void processAttributes(Style style, TypedArrayWrapper a) {
    // ...
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES. JELLY_BEAN_MR1 &&
            a.hasValue(R.styleable.Paris_View_android_layout_marginEnd)) {
      getProxy().setLayoutMarginEnd(a.getDimensionPixelSize(R.styleable.Paris_View_android_layout_marginEnd));
    }
    // ...
  }
```

If you don't, I'll fix it myself, but it might take a few days at best.

**Comment by kristiyanP** [comment]
> @kristiyanP your repro steps for the sample app, is that without modifying R.style.Blue? If so, I don't see what's not compatible with API v16 in there. 🤔

Yes without modifying the R.style.Blue.

It seems a platform bug as on api16, Paris_android_layoutMarginEnd/Start is the offset to a different resource, my guess is that after api16 they removed/changed that resource and replaced with layoutMarginStart/End.

> If you don't, I'll fix it myself, but it might take a few days at best.
The solution you proposed looks nice!  But I think will not be enough in same cases.
We have to put the check before we try to get the attribute value to prevent crashes as what happened to @plnice. 

Elevation for example should be applied no matter what... as is part of the ViewCompat but my guess is that Samsung in that case added some attribute with the same exact id as it was a free one at that time and now that ViewCompat tries to fetch it it returns a different type of resource, instead of saying that there is no such attribute.

If it sounds good to you, I will submit a PR.

**Comment by ngsilverman** [comment]
@kristiyanP oh I see, I think I understand what you mean now. Yeah that sounds like it could cause this issue. So, the check I'm proposing would happen before the attribute value is accessed, so I still think it's the best solution at this point. I can look into it today.

**Comment by ngsilverman** [comment]
@kristiyanP take a look at #72 first. 😉

**Comment by kristiyanP** [comment]
Nice! I will reply on the #72
