### ISSUE TITLE
Coloring buttons

### ISSUE THREAD

**Issue by qbait** [airbnb/paris#79]
I've just started using `Paris`, that's such a clever addition for `Epoxy`, thank you!

I would like to style the background color of my buttons.
This is my Model
```
@Styleable("Button")
@ModelView(autoLayout = ModelView.Size.MATCH_WIDTH_WRAP_HEIGHT)
class Button @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0
) : LinearLayout(context, attrs, defStyleAttr) {

    @StyleableChild(R.styleable.Button_buttonStyle)
    val button by lazy { findViewById<android.widget.Button>(R.id.button) }

    init {
        inflate(context, R.layout.button, this)
    }

    companion object {
        @Style(isDefault = true)
        val RED_STYLE = R.style.RedButton

        @Style
        val BLUE_STYLE = R.style.BlueButton
    }
}
```

This is my attrs.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <declare-styleable name="Button">
        <attr name="buttonStyle" format="reference" />
    </declare-styleable>
</resources>
```

And these are my styles
```
    <style name="RedButtonTheme" parent="Theme.AppCompat">
        <item name="colorButtonNormal">@color/red</item>
    </style>

    <style name="BlueButtonTheme" parent="Theme.AppCompat">
        <item name="colorButtonNormal">@color/blue</item>
    </style>

    <style name="RedButton" parent="Theme.AppCompat">
        <item name="android:theme">@style/RedButtonTheme</item>
    </style>

    <style name="BlueButton" parent="Theme.AppCompat">
        <item name="android:theme">@style/BlueButtonTheme</item>
    </style> 
```

Unfortunately, it doesn't set correctly background for buttons.

I'm guessing that's the issue with my styles.xml, because these sample styles were working
```
    <style name="RedButton">
        <item name="buttonStyle">@style/Widget.AppCompat.Button.Colored</item>
    </style>
    <style name="BlueButton">
        <item name="buttonStyle">@style/Widget.AppCompat.Button</item>
    </style>
```

**Comment by ngsilverman** [comment]
@qbait although they're declared in the same way, **themes** and **styles** are two separate things.

Themes, like `Theme.AppCompat`, can be used on Activities in the manifest, for example:
```xml
<activity android:theme="@android:style/Theme.AppCompat">
```
Applying them with Paris will do nothing.

To change the color of the buttons using Paris you could create button styles from scratch:
```xml
<style name="RedButton">
    <item name="android:background">@drawable/your_red_background</item>
    <item name="android:textColor">...</item>
    ...
</style>
```
Or you could extend a style like `@style/Widget.AppCompat.Button`. For reference, this is how the Android platform does it:
```xml
<style name="Base.Widget.AppCompat.Button.Colored">
    <item name="android:background">@drawable/abc_btn_colored_material</item>
    <item name="android:textAppearance">@style/TextAppearance.AppCompat.Widget.Button.Inverse</item>
</style>
```

And this is the background asset it uses, `abc_btn_colored_material.xml`: https://chromium.googlesource.com/android_tools/+/febed84a3a3cb7c2cb80d580d79c31e22e9643a5/sdk/extras/android/support/v7/appcompat/res/drawable-v21/abc_btn_colored_material.xml

Notices how it uses an attribute value from the theme:
```xml
...
<solid android:color="?android:attr/colorButtonNormal"/>
...
```

Themes basically declare variables that styles can use. Similarly a style defined like this would work with Paris, and would use the button color defined in whatever theme is used in the current Activity:
```xml
<style name="MyButton">
    <item name="android:background">?android:attr/colorButtonNormal</item>
    ...
</style>
```

----

In theory we could make it possible to specify a theme as we're applying a style with Paris, but that's not something I've had a chance to look into yet.

**Comment by qbait** [comment]
Thank you @ngsilverman. Really appreciate your detailed answer, especially that at the end I had a problem with android themes, not `Paris` :)
