### ISSUE TITLE
XML styles not working

### ISSUE THREAD

**Issue by kshirsagarps** [airbnb/paris#84]
Hello @alexism and @schleyfox,
I am creating a sample app to try Paris, so that I can introduce it to my team. Somehow it seems the styling is not getting applied in my sample both XML and programmatically. I see that moving my views and style to the sample provided in the Paris Repo works fine.
It will be great help if you can review the sample and give a quick feedback so that I can move further in my exploration. Link to the Paris Sample - https://github.com/kshirsagarps/airbnb_paris_sample

**Comment by ngsilverman** [comment]
@kshirsagarps good catch! Could you test:

```
implementation "com.airbnb.android:paris:1.1.0"
kapt "com.airbnb.android:paris-processor:1.1.0"
```

That should work as well.

**Comment by kshirsagarps** [comment]
Works well 👍
FYI, I am working on a sample app where I have my views in a module a.k.a android library. I also tried writing unit tests to simulate a style factory or presenters building and setting up styles. Let me know if it's good to have a similar example in our Paris sample or a link to my sample (WIP). I am sure engineers gonna love it (we all love unit tests), will make setting up styles robust and will have more Paris lovers 😉

**Comment by ngsilverman** [comment]
@kshirsagarps I'd be happy to take a look at the code, not sure I completely understand what you're doing but sounds cool. 😄

**Comment by kshirsagarps** [comment]
@ngsilverman sure will share the code.

**Comment by ngsilverman** [comment]
@kshirsagarps I see. If you wanted to get the list of attributes and their value you could call `style.obtainStyledAttributes(…)`, but I don't think you need to.

Consider what you're testing here. Paris already has tests that assert that styles are created correctly. Assuming the logic in `getIconStyle` is fairly simple then the additional testing your test provides is minimal.
