### ISSUE TITLE
Migrate to androidx

### ISSUE THREAD

**Issue by jeffreydelooff** [airbnb/paris#85]
Epoxy is depending on this library and cannot yet be fully migrated to androidx.

Blocks https://github.com/airbnb/epoxy/issues/429 and https://github.com/airbnb/epoxy/pull/440

**Comment by ngsilverman** [comment]
Thanks for creating an issue. I'm working on it at the moment. 😄

**Comment by ngsilverman** [comment]
@jeffreydelooff done. I'll publish a new release soon.

**Comment by jeffreydelooff** [comment]
Great, if you publish a release I'll be able to update epoxy. Good job, that was pretty fast. :)

**Comment by ngsilverman** [comment]
@jeffreydelooff all done.
